version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/project

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Tests unitaires
          command: npm run test

  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Build du projet
          command: npm run build

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build